DROP TABLE IF EXISTS Category CASCADE;
CREATE TABLE Category (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) UNIQUE NOT NULL,
	description VARCHAR(255) DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Product CASCADE;
CREATE TABLE Product (
	id SERIAL PRIMARY KEY,
	name VARCHAR(150) UNIQUE NOT NULL,
	description VARCHAR(200) DEFAULT '',
	size VARCHAR(5) NOT NULL,
	color VARCHAR(20) NOT NULL,
	price INTEGER DEFAULT 0,
	attribute VARCHAR(100) NOT NULL,
	selled BOOLEAN DEFAULT FALSE,
	category_id INTEGER NOT NULL,
	image TEXT DEFAULT '',
	CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE Users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(150) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	kind VARCHAR(100) DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ShopCard CASCADE;
CREATE TABLE ShopCard(
	id SERIAL PRIMARY KEY,
	description VARCHAR(255) DEFAULT '',
	product_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE CASCADE,
	CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Payment CASCADE;
CREATE TABLE Payment (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Orders CASCADE;
CREATE TABLE Orders(
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,    
	payment_id INTEGER NOT NULL, 
	email VARCHAR(150) NOT NULL,
	delivery VARCHAR(255) DEFAULT '',
	totalprice INTEGER DEFAULT 0,
	state VARCHAR(20) NOT NULL,
	
	CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
	CONSTRAINT fk_order_payment FOREIGN KEY (payment_id) REFERENCES Payment(id) ON DELETE RESTRICT,
	
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_product_price ON Product(price);
CREATE INDEX idx_product_size ON Product(size);